FROM debian:bullseye-slim as base
ARG VERSION=4.0.11
ARG CHECKSUM=eb63a40f94d96fe7c7e3dcc497f7bbc2978cd7df
WORKDIR /
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN \
  echo "**** install basic packages ****" && \
  apt-get update && \
  apt-get install -y --no-install-recommends \
    unzip \
    ca-certificates \
    wget && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  echo "**** download formalms ****" && \
  wget -O formalms.zip https://sourceforge.net/projects/forma/files/version-4.x/formalms-${VERSION}.zip/download && \
  echo "${CHECKSUM}  formalms.zip" | sha1sum -c && \
  unzip formalms.zip && \
  rm formalms.zip && \
  cp /formalms/config.dist.php /formalms/config.php

FROM php:8.1-apache-bullseye as php

ENV APACHE_DOCUMENT_ROOT /app
WORKDIR /app
COPY --from=base /formalms .
#ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
#RUN install-php-extensions pdo mysqli pdo_mysql 
RUN \
  echo "**** install final packages ****" && \
  apt-get update && \
  apt-get install -y --no-install-recommends \
    dnsutils \
    iproute2 \
    vim && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  docker-php-ext-configure mysqli && \
  docker-php-ext-install mysqli && \
  docker-php-ext-install pdo pdo_mysql && \
  docker-php-ext-enable pdo_mysql && \
  sed -ri -e "s!/var/www/html!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/sites-available/*.conf && \
  sed -ri -e "s!/var/www/!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf && \
  chown www-data:www-data -R /app
VOLUME /app
EXPOSE 80 443
