FROM debian:bullseye-slim as base
#FROM eilandert/debian-base:bullseye as base
#  wget -qO /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg && \
ARG VERSION=4.0.11
ARG CHECKSUM=eb63a40f94d96fe7c7e3dcc497f7bbc2978cd7df
WORKDIR /
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN \
  echo "**** install php8.1-mysql 1 packages ****" && \
  apt-get update && \
  apt-get install -y --no-install-recommends wget gnupg && \
  echo "deb [trusted=yes] http://edge.deb.myguard.nl:8888/mirror/ondrej-php bullseye main"  > /etc/apt/sources.list.d/ondrej-ppa.list && \
  apt-get update && \
  apt-get install -o Debug::pkgProblemResolver=true  -o Debug::Acquire::http=true -o Debug::pkgDepCache::Marker= -m -y --no-install-recommends php8.1-mysql

FROM php:8.1-apache-bullseye as php

ENV APACHE_DOCUMENT_ROOT /app
WORKDIR /app
RUN \
  echo "**** install php8.1-mysql 2 packages ****" && \
  apt-get update && \
  apt-get install -y --no-install-recommends wget gnupg && \
  echo "deb [trusted=yes] http://edge.deb.myguard.nl:8888/mirror/ondrej-php bullseye main"  > /etc/apt/sources.list.d/ondrej-ppa.list && \
  apt-get update && \
  apt-get install -o Debug::pkgProblemResolver=true -o Debug::Acquire::http=true -o Debug::pkgDepCache::Marker= -m -y --no-install-recommends php8.1-mysqli
VOLUME /app
EXPOSE 80 443
