secrets:
  ldap_bind_pw_portainer:
    file: $SECRETS_PATH/ldap_bind_pw.txt
services:

  formalms:
    image: marioja/formalms
    restart: unless-stopped
    ports:
      - 7080:80
    volumes:
      - formalms:/app
    environment:
      PUID: 1001
      GUID: 1001
      # LDAP Configuration
      LDAP_HOST: "ldap.mfj.local"
      LDAP_PORT: "389"
      LDAP_BASE_DN: "dc=mfj,dc=c2,dc=us"
      LDAP_BIND_DN: "cn=95fb0983-0e5a-4d70-824c-3cc0bb0b4776,cn=nasAccount,cn=Syno,dc=mfj,dc=c2,dc=us"
      LDAP_USER_FILTER: "(&(objectClass=person)(uid=%u))"
      LDAP_USERNAME_ATTRIBUTE: "uid"
      LDAP_REALNAME_ATTRIBUTE: "cn"
      LDAP_EMAIL_ATTRIBUTE: "mail"
    entrypoint: [
      "/bin/sh", 
      "-c", 
      "ldap-config.sh"
    ]

  db:
    image: mariadb:10.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_SQL_MODE: NO_ENGINE_SUBSTITUTION
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  formalms: