services:

  formalms:
    image: marioja/formalms
    restart: unless-stopped
    ports:
      - 7080:80
    volumes:
      - formalms:/app
    environment:
      PUID: 1001
      GUID: 1001
    entrypoint: [
      "/bin/sh", 
      "-c", 
      "sed -i \"s|cfg\\['db_host'\\] = 'localhost'|cfg['db_host'] = '${DB_HOST}'|\" /app/formalms/config.php && sed -i \"s|cfg\\['db_user'\\] = 'root'|cfg['db_user'] = '${DB_USER}'|\" /app/formalms/config.php && sed -i \"s|cfg\\['db_pass'\\] = ''|cfg['db_pass'] = '${DB_PASS}'|\" /app/formalms/config.php && sed -i \"s|cfg\\['db_name'\\] = 'forma'|cfg['db_name'] = '${DB_NAME}'|\" /app/formalms/config.php && apache2-foreground"
    ]

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_SQL_MODE: NO_ENGINE_SUBSTITUTION
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  formalms: