secrets:
  formalms_db_pw:
    file: $SECRETS_PATH/formalms_db_pw.txt
services:

  db:
    image: mariadb:10.3
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 10s
      retries: 20
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_SQL_MODE: NO_ENGINE_SUBSTITUTION
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    volumes:
      - db:/var/lib/mysql
  formalms:
    image: marioja/formalms
    secrets:
      - formalms_db_pw
    restart: unless-stopped
    ports:
      - 7080:80
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - formalms:/app
      - /mnt/nasshare/portainer/data/formalms-4.0.11:/data
    environment:
      PUID: 1001
      GUID: 1001
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      # LDAP Configuration
      LDAP_HOST: "${LDAP_HOST}"
      LDAP_PORT: "389"
      LDAP_USER_STRING: "${LDAP_USER_STRING}"
      # The next two variables have the value "on" or "off"
      LDAP_ALTERNATE_CHECK: "on"
      LDAP_USED: "on"
    entrypoint: [
      "/bin/sh", 
      "-c", 
      "ldap-config.sh"
    ]

volumes:
  db:
  formalms: